// Generated by https://quicktype.io

export interface PublicationResponse {
  results: Results;
}

export interface Results {
  count: number;
  totalPages: number;
  currentPage: number;
  results: Publication[];
}

export interface Publication {
  id: string;
  user_id: string;
  publication_type_id: number;
  city_id: number;
  title: string;
  description: string;
  content: string;
  reference_link: string;
  created_at: string;
  updated_at: string;
  votes_count: number;
  user: User;
  publication_type: PublicationType;
  images: Image[];
  tags: PublicationType[];
}

export interface PublicationPost {
  id: string;
  title: string;
  description: string;
  reference_link: string;
  images: Image[];
  votes_count: number;
  // isVoted: boolean;
  // same_vote: any[];
}
/*this was created by me */
export interface PublicationForm {
  title: string;
  publication_type_id: string;
  content: string;
  description: string;
  reference_link: string;
  tags: string;
}
/*this also */
export interface ImagesUpload {
  images: FileList;
}
/*this also */
export interface ImageUpload {
  image_url: string;
}

export interface Image {
  publication_id: string;
  image_url: string;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface PublicationType {
  id: number;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  image_url: null;
}

export interface User {
  first_name: string;
  last_name: string;
  image_url: null;
}
